about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_posts'),
    path('new/',
         views.post_new,
         name='post_new'),
    path('follow/',
         views.follow_index,
         name='follow_index'),
    path('<str:username>/',
         views.profile,
         name='profile'),
    path('<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
    path('<str:username>/<int:post_id>/',
         views.post_view, name='post'),
    path('<str:username>/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('<str:username>/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('', views.index, name='index')]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'  # noqa

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts'))]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

posts/models.py
import textwrap

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Сообщество."""
    title = models.CharField(
        'название группы',
        max_length=200,
        help_text='Придумайте краткое и ёмкое название для группы сообщений')
    slug = models.SlugField(
        unique=True,
        max_length=100,
        verbose_name='url group',
        help_text='Краткое, уникальное слово, которое будет '
                  'видно в ссылке на страницу группы (часть URL)')
    description = models.TextField(
        'описание',
        help_text='Опишите группу так, чтобы пользователь мог легко  '
                  'определиться с выбором группы для сообщения.')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'posts_group'
        verbose_name = 'group'
        verbose_name_plural = 'Группа'


class Post(models.Model):
    """Публикация пользователя."""

    image = models.ImageField(upload_to='posts/', blank=True, null=True)

    text = models.TextField(
        'сообщение',
        default='ваш текст',
        help_text='Напишите, что вы думаете по этой теме.')
    pub_date = models.DateTimeField(
        'дата публикации',
        auto_now_add=True,
        help_text='Дата публикации сообщения на сайте.',
        db_index=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='автор',
        help_text='Пользователь оставивший сообщение.',
        related_name='author_posts')
    group = models.ForeignKey(
        'Group',
        models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='группа',
        help_text='Группа сообщений.',
        related_name='group_posts')

    def __str__(self):
        return [f'author: {self.author}, '
                f'group: {self.group}, '
                f'pub_date: {self.pub_date}, '
                f'text: {textwrap.wrap(self.text[:15])}']

    class Meta:
        db_table = 'posts_post'
        ordering = ('-pub_date',)
        verbose_name = 'post'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        verbose_name='пост',
        help_text='Сообщение.',
        related_name='comment_post')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='автор',
        help_text='Пользователь оставивший комментарий.',
        related_name='author_comment')
    text = models.TextField(
        'комментарий',
        default='ваш текст',
        help_text='Напишите, что вы думаете по этой теме.')
    created = models.DateTimeField(
        'дата и время публикации',
        auto_now_add=True,
        help_text='дата и время публикации комментария на сайте.')

    def __str__(self):
        return [f'author: {self.author}, '
                f'post: {self.post}, '
                f'created: {self.created}, '
                f'text: {textwrap.wrap(self.text[:15])}']

    class Meta:
        db_table = 'comment'
        verbose_name = 'comment'
        ordering = ('-created',)
        verbose_name_plural = 'Комментарий'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='подписчик',
        help_text='Пользователь, который подписывается.',
        related_name='follower')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='автор',
        help_text='Пользователь, на которого подписываются.',
        related_name='following')

    def __str__(self):
        return [f'user: {self.user}, '
                f'author: {self.author}']

    class Meta:
        db_table = 'follow_author'
        verbose_name = 'follow'
        ordering = ('-author',)
        verbose_name_plural = 'Подписки'

posts/forms.py
from django import forms

from .models import Post, Comment


def clean_artist(value):
    if value == '':
        raise forms.ValidationError(
            'А кто поле будет заполнять, Пушкин?',
            params={'value': value})


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = 'text',

posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator

from yatube.settings import COUNT_PAGE
from .forms import PostForm, CommentForm
from .models import Group, Post, User, Comment, Follow


def pagination_page(request, post_list=None, pages=COUNT_PAGE):
    """Определяет кол-во страниц и записей на них."""
    if post_list is None:
        post_list = {}
    paginator = Paginator(post_list, pages)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    post_list = pagination_page(request, Post.objects.all())
    return render(request, 'index.html', {'page': post_list, 'index': True})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = pagination_page(request, Post.objects.filter(group=group))
    return render(request, 'group.html',
                  {'group': group, 'page': post_list})


def profile(request, username):
    user = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=user)
    user_following = Follow.objects.filter(author_id=user.id).values_list(
        'author_id', flat=True).count()
    following = Follow.objects.filter(
        user_id=request.user.id, author_id=user.id).count()
    follow = Follow.objects.filter(user_id=user.id).count()
    context = {
        'author': user,
        'count_posts': post_list.count(),
        'page': pagination_page(request, post_list),
        'following': following,
        'follow': follow,
        'user_following': user_following}
    return render(request, 'profile.html', context)


def post_view(request, username, post_id):
    user = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=user)
    comment_list = Comment.objects.filter(post=post_id)
    form = CommentForm(request.POST or None)
    post = Post.objects.get(pk=post_id)
    context = {
        'author': post.author,
        'text': post,
        'post_id': post.id,
        'comment_list': comment_list,
        'form': form,
        'count_posts': post_list.count()}
    return render(request, 'post.html', context)


@login_required
def post_new(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form and form.is_valid():
        form.instance.author = request.user
        form.save()
        return redirect('posts:index')
    return render(
        request, 'post_new.html',
        {'form': form, 'title': 'Добавить', 'button': 'Добавить'})


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None, files=request.FILES or None,
                    instance=post)
    if post.author != request.user:
        return redirect('posts:post', username=username, post_id=post_id)
    if form and form.is_valid():
        post = form.save(commit=False)
        post.save()
        return redirect('posts:post', username=username, post_id=post_id)
    return render(
        request, 'post_new.html', {'form': form, 'post': post,
                                   'title': 'Редактировать',
                                   'button': 'Сохранить'})


def page_not_found(request, exception):
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=404
    )


def server_error(request):
    return render(request, 'misc/500.html', status=500)


@login_required
def add_comment(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form and form.is_valid():
        form.instance.author = request.user
        form.instance.post = post
        form.save()
        return redirect('posts:post', username=username, post_id=post_id)
    return render(request, 'comments.html', {'form': form})


@login_required
def follow_index(request):
    """Посты авторов на которых подписан пользователь."""
    authors = Follow.objects.filter(user_id=request.user.id).values_list(
        'author_id', flat=True)
    username = User.objects.filter(id__in=authors)
    post_list = pagination_page(request, Post.objects.filter(
        author__in=username))
    return render(request, 'follow.html', {'page': post_list, 'follow': True})


@login_required
def profile_follow(request, username):
    """Подписка на интересного автора."""
    user = get_object_or_404(User, username=username)
    following = Follow.objects.filter(
        user_id=request.user.id, author_id=user.id).count()
    if request.user.id != user.id and following < 1:
        follow = Follow(user=request.user, author=user)
        follow.save()
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    user = get_object_or_404(User, username=username)
    Follow.objects.filter(user_id=request.user.id, author_id=user.id).delete()
    return redirect('posts:follow_index')

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need
        {% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet"
          href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
{% include 'includes/nav.html' %}
<main>
    <div class="container">
        {% block header %}The Last Social Media You'll Ever Need{% endblock %}
        {% block content %}
        <!-- Содержимое страницы -->
        {% endblock %}
    </div>
</main>
{% include 'includes/footer.html' %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

templates/comments.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{group}}{% endblock %}
{% block header %}<h1>{{group}}</h1>{% endblock %}
{% load user_filters %}
{% block content %}



{% include "includes/form_comment.html" with form=form %}


<!-- Комментарии -->
{% for item in comments %}
    <div class="media card mb-4">
        <div class="media-body card-body">
            <h5 class="mt-0">
                <a href="{% url 'post:profile' item.author.username %}"
                   name="comment_{{ item.id }}">
                    {{ item.author.username }}
                </a>
            </h5>
            <p>{{ item.text | linebreaksbr }}</p>
        </div>
    </div>
{% endfor %}

{% endblock %}

templates/follow.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}Моя подписка{% endblock %}
{% block header %}<h1>Моя подписка</h1>{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
       {% include "includes/menu.html" %}
    {% endif %}
       {% for post in page %}
           {% include "includes/post_item.html" with post=post %}
       {% endfor %}
    {% include "includes/paginator.html" %}
{% endblock %}

templates/group.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Записи сообщества {{group}}{% endblock %}
{% block header %}<h1>{{group}}</h1>{% endblock %}

{% block content %}

<p>
    {{group.description}}
</p>
{% for post in page %}
    {% include "includes/post_item.html" with post=post %}
{% endfor %}

{% include "includes/paginator.html" %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache %}

{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}<h1>Последние обновления на сайте</h1>{% endblock %}
{% block content %}
    {% include "includes/menu.html" %}
    {% cache 20 index_page %}
        {% for post in page %}
            {% include "includes/post_item.html" with post=post %}
        {% endfor %}
    {% endcache %}
    {% include "includes/paginator.html" %}
{% endblock %}

templates/post.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Запись {{ username }}{% endblock %}
{% block header %}
    <div></div>{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-3 mb-3 mt-1">
            {% include 'includes/card_user.html' %}
        </div>
        <div class="col-md-9">
            <div class="card mb-3 mt-1 shadow-sm">

                {% thumbnail text.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img" src="{{ im.url }}">
                {% endthumbnail %}
                <div class="card-body">
                    <p class="card-text">
                        <a href="/{{ author }}"><strong class="d-block text-gray-dark">@{{ author }}</strong></a>
                        {{ text.text }}
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group ">
                            {% if request.user == author %}
                                <a class="btn btn-sm text-muted"
                                   href="/{{ author }}/{{ post_id }}/edit/"
                                   role="button">Редактировать</a>
                            {% endif %}
                        </div>
                        <!-- Дата публикации  -->
                        <small class="text-muted">
                            {{ text.pub_date|date:"d F Y г. H:i" }}</small>
                    </div>
                </div>
            </div>
                {% for comment in comment_list %}
                    <div class="card mb-3 mt-1 shadow-sm">
                        {{ comment.text }}
                    </div>
                {% endfor %}

        </div>

    </div>


{% endblock %}

templates/post_new.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{group}}{% endblock %}
{% block header %}<h1>{{group}}</h1>{% endblock %}
{% load user_filters %}
{% block content %}

<p>
    {{group.description}}
</p>


<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{{title}} запись</div>
            <div class="card-body">

                {% for error in form.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error|escape }}
                </div>
                {% endfor %}

                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group row"
                         aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                    <label for="{{ field.id_for_label }}"
                           class="col-md-4 col-form-label text-md-right">
                        {{ field.label }}
                        {% if field.field.required %}
                            <span class="required">*</span>
                        {% endif %}
                    </label>
                    <div class="col-md-6">
                        {# подключаем фильтр и указываем класс #}
                        {{ field|addclass:"form-control" }}

                        {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help"
                                   class="form-text text-muted">
                                {{ field.help_text|safe }}
                            </small>
                        {% endif %}
                    </div>
            </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{button}}
                </button>
            </div>
            </form>
        </div> <!-- card body -->
    </div> <!-- card -->
</div>

<!--<form method="post">-->
<!--    {% csrf_token %}-->
<!--    {{ form.as_p }}-->
<!--    <input type="submit" value="Отправить">-->
<!--</form>-->

{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Профиль {{ author }}{% endblock %}
{% block header %}
    <div></div>{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-3 mb-3 mt-1">
            {% include 'includes/card_user.html' %}
        </div>
        <div class="col-md-9">
            {% for post in page %}
                {% include "includes/post_item.html" with post=post %}
            {% endfor %}
            {% include "includes/paginator.html" %}
        </div>
    </div>

{% endblock %}